package org.openmrs.module.ncd.database;

// Generated Aug 27, 2008 7:12:14 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.openmrs.module.ncd.database.filter.ListPageRow;

/**
 * ReportableResult generated by hbm2java
 */
public class ReportableResult implements java.io.Serializable, ListPageRow 
{
	private static final long serialVersionUID = 2083949300031403756L;
	/** The synthetic primary key */
    private Long id;
    /** The encounter_id for the associated OpenMRS Encounter */
    private Long encounterId;
    /** The name of the condition being reported, or null if the exact
     * condition could not be identified. */
    private String conditionName;
    /** The (LOINC) code that drove reporting this result. */
    private Code code;
    /** The previous reportable result */
    private ReportableResult previousReportableResult;
    /** The Institution that owns the HL7Producer that sent the message
     * that generated this reportable result, or null if the Institution or
     * HL7Producer could not be identified. */
    private Institution institution;
    /** The type of the Institution that owns the HL7Producer that sent the
     * message that generated this reportable result, or null if the
     * Institution or HL7Producer could not be identified. */
    private String institutionIdType;
    /** The message that generated this reportable result */
    private RawMessage rawMessage;
    /** The HL7Producer that sent the message that generated this
     * reportable result */
    private HL7Producer producer;
    /** The sending facility from the message that generated this reportable
     * result */
    private String facilityId;
    /** The patient's home county as inferred from the message that generated
     * this reportable result. */
    private County county;
    /** The health department having case jurisdiction, as inferred from the
     * message that generated this reportable result. */
    private Jurisdiction jurisdiction;
    /** The critic that generated this reportable result */
    private CriticDef critic;
    /** The archived DecidedResult that generated this reportable result, if the
     * decided result critic generated this reportable result. */
    private DecidedResultArchive decidedResult;
    /** The unique ID assigned to the message that generated this reportable
     * result by the upstream pipeline (the Message Processing Queue or
     * MPQ) */
    private String mpqSeqNumber;
    /** The date and time this message was received by the Message
     * Processor */
    private Date messageReceivedDateTime;

    /** A unique ID assigned this reportable result at the time it is
     * created, in increasing order over time. When the manual review status
     * of this reportable result is changed, a new unique ID will be
     * assigned. This ID is used by the export logic to order reportable
     * results in time, and to remember the last reportable result
     * exported */
    private Long resultSeq;
    /** The manual review status of this reportable result. */
    private ManualReviewStatusType manualReviewStatusType;
    /** The date and time this message was released for export. This is
     * the same as messageReceivedDateTime if the message did not require manual
     * review in the first place, the date and time its manual review
     * status was changed from "hold" to "release", or null in any other
     * situation. */
    private Date releaseDate;
    
    /** The medical record ID assigned to the patient associated with the
     * message that generated this reportable result, by the associated
     * Institution. */
    private String patientInstitutionMedicalRecordId;
    /** The globally unique patient ID of the patient */ 
    private String globalPatientId;
    /** The patient's Social Security Number */
    private String patientSSN;
    /** The patient's name */
    private String patientName;
    /** The patient's date of birth */
    private Date patientBirth;
    /** The patient's race */
    private String patientRace;
    /** The patient's contact phone number */
    private String patientPhone;
    /** The patient's contact street address, line 1 */
    private String patientStreet1;
    /** The patient's contact street address, line 2 */
    private String patientStreet2;
    /** The patient's contact city */
    private String patientCity;
    /** The patient's contact county */
    private String patientCounty;
    /** The patient's contact state */
    private String patientState;
    /** The patient's contact zip code */
    private String patientZip;
    /** The patient's contact country */
    private String patientCountry;
    /** The patient's gender */
    private Character patientSex;

    /** The name of the provider in the candidate result that generated
     * this reportable result. */
    private String providerName;
    /** The message field from which the provider name was taken */
    private String providerNameSource;
    /** The name of the provider after passing through the matcher. */
    private String providerNameMatched;
    /** The provider's Social Security Number */
    private String providerSSN;
    /** The provider's date of birth */
    private Date providerBirth;
    /** The name of the provider's practice */
    private String providerPractice;
    /** The provider's contact street address */
    private String providerStreet;
    /** The provider's contact city */
    private String providerCity;
    /** The provider's contact state */
    private String providerState;
    /** The provider's contact zip code */
    private String providerZip;
    /** The provider's contact county */
    private String providerCounty;
    /** The provider's contact phone number */
    private String providerPhone;
    /** The message field from which the provider contact address was taken */
    private String providerAddressSource;
    /** The provider's "local id"
     * Who assigns this? The institution?
     */
    private String providerLocalId;
    /** The message field from which the provider local id was taken */
    private String providerLocalIdSource;
    /** The provider's medical license number */
    private String providerLicense;
    /** The provider's DEA prescriber ID */
    private String providerDEANumber;

    /** The name of the laboratory that performed the tests that generated
     * the message that generated this reportable result */
    private String labName;
    /** The laboratory's identifier (assigned by who?) */
    private String labId;
    /** The laboratory's contact phone number */
    private String labPhone;
    /** The laboratory's contact street address line 1 */
    private String labStreet1;
    /** The laboratory's contact street address line 2 */
    private String labStreet2;
    /** The laboratory's contact address city */
    private String labCity;
    /** The laboratory's contact address state */
    private String labState;
    /** The laboratory's contact address zip code */
    private String labZip;

    /** The id of the test that was performed */
    private String testId;
    /** The name of the test that was performed */
    private String testName;
    /** The code system used for test results */
    private String testCodeSystem;
    /** The order number assigned to the test order by order placer */
    private String testPlacerOrderNum;
    /** The message field from which the placer order number was taken */
    private String testPlacerOrderNumSource;
    /** The order number assigned to the test order by order filler */
    private String testFillerOrderNum;
    /** The message field from which the filler order number was taken */
    private String testFillerOrderNumSource;
    /** The date and time the test was performed (?) */
    private Date testDate;
    /** The message field from which the test date was taken */
    private String testDateSource;
    /** The order number assigned the test's parent by the order placer */
    private String testParentPlacer;
    /** The order number assigned the test's parent by the order filler */
    private String testParentFiller;
    /** Description of the test specimen */
    private String testSpecimenText;
    /** The HL7 data type name for the test data */
    private String testDataType;
    /** The normal range of values for the test result */
    private String testNormalRange;
    /** The value of the HL7 abnormal result flag for the test result */
    private String testAbnormalFlag;
    /** Free-text comments about the test */
    private String testComment;
    /** The id of the test result */
    private String testResultId;
    /** The name of the test result */
    private String testResultName;
    /** The code for the test result */
    private String testResultCode;
    /** The code system for the test result */
    private String testResultCodeSystem;
    /** The sub-id for the test result id */
    private String testResultSubId;
    /** The value of the test result */
    private String testResultValue;
    /** The units in which the value of the test result is expressed */
    private String testResultUnits;
    /** The date on which a previous test was performed */
    private Date testPreviousDate;
    /** A one character code indicating the status of the test result, e.g.,
     * preliminary, final, revised, or in error. */
    private Character testResultStatus;

    /** The non-LOINC-mapped code from the OBR segment of the candidate
     * result that generated this reportable result. */
    private String obrAltCode;
    /** The non-LOINC-mapped free text from the OBR segment of the candidate
     * result that generated this reportable result. */
    private String obrAltCodeText;
    /** The non-LOINC-mapped code system from the OBR segment of the 
     * candidate result that generated this reportable result. */
    private String obrAltCodeSystem;
    /** The non-LOINC-mapped code from the OBX segment of the candidate
     * result that generated this reportable result. */
    private String obxAltCode;
    /** The non-LOINC-mapped free text from the OBX segment of the candidate
     * result that generated this reportable result. */
    private String obxAltCodeText;
    /** The non-LOINC-mapped code system from the OBX segment of the 
     * candidate result that generated this reportable result. */
    private String obxAltCodeSystem;
    /** The index of the OBR segment that generated this reportable result. */
    private int obrSetId;
    /** The index of the first OBX segment that generated this reportable
     * result. */
    private int obxStartSetId;
    /** The index of the last OBX segment that generated this reportable
     * result. */
    private int obxEndSetId;
    /** The HL7 sending application field from the message that generated
     * this reportable result. */
    private String sendingApplication;
    /** The HL7 sending facility field from the message that generated
     * this reportable result. */
    private String sendingFacility;
    /** The HL7 sending location field from the message that generated
     * this reportable result. */
    private String sendingLocation;
    /** A flag indicating whether or not the reportable result has been sent in error */
    private Boolean sentInError;
    /** A denormalized column containing the display value for the critic on the reportable results list page */
    private String criticDisplay;
    /** A denormalized column containing the display value for the LOINC code on the reportable results list page */
    private String codeDisplay;
    /** The set of reportable results for which this result is "the previous" */
    private Set<ReportableResult> nextReportableResults = new HashSet<ReportableResult>(
            0);

    public ReportableResult() 
    {
    }    
    
    public String diagnosticOutput()
    {
        StringBuilder out = new StringBuilder();
        
        out.append( "\n----------------------------" );
        out.append( "\n      ReportableResult      " );
        out.append( "\n----------------------------" );
        out.append( "\n criticName                =" );
        out.append( this.criticDisplay != null ? this.critic.getName() : "" );
        out.append( "\n criticId                  =" );
        out.append( this.critic != null ? this.critic.getId() : "" );
        out.append( "\n decidedResult             =" + this.decidedResult );
        out.append( "\n conditionName             =" + this.conditionName );
        out.append( "\n resultSeq                 =" + this.resultSeq );
        out.append( "\n criticDisplay             =" + this.criticDisplay );
        out.append( "\n codeDisplay               =" + this.codeDisplay );
        out.append( "\n----------------------------" );
        out.append( "\n code                      =" );
        out.append( this.code != null ? this.code.getCode() : "" );
        out.append( "\n patientName               =" + this.patientName );
        out.append( "\n providerName              =" + this.providerName );
        out.append( "\n----------------------------" );
        out.append( "\n Date                      =" + new java.util.Date() );
        out.append( "\n----------------------------" );
        out.append( "\n previousReportableResult:\n" + this.previousReportableResult );
        out.append( "\n----------------------------" );
        
        return out.toString(); 
    }

    /** copy constructor */
    public ReportableResult(ReportableResult copy)
    {
        this.id                                 = copy.id;
        this.rawMessage                         = copy.rawMessage;
        this.producer                           = copy.producer;
        this.code                               = copy.code;
        this.institution                        = copy.institution;
        this.previousReportableResult           = copy.previousReportableResult;
        this.county                             = copy.county;
        this.jurisdiction                       = copy.jurisdiction;
        this.critic                             = copy.critic;
        this.decidedResult                      = copy.decidedResult;
        this.manualReviewStatusType             = copy.manualReviewStatusType;
        this.institutionIdType                  = copy.institutionIdType;
        this.patientInstitutionMedicalRecordId  = copy.patientInstitutionMedicalRecordId;
        this.globalPatientId                    = copy.globalPatientId;
        this.patientSSN                         = copy.patientSSN;
        this.patientName                        = copy.patientName;
        this.patientBirth                       = copy.patientBirth;
        this.patientSex                         = copy.patientSex;
        this.patientRace                        = copy.patientRace;
        this.patientPhone                       = copy.patientPhone;
        this.patientStreet1                     = copy.patientStreet1;
        this.patientStreet2                     = copy.patientStreet2;
        this.patientCity                        = copy.patientCity;
        this.patientCounty                      = copy.patientCounty;
        this.patientState                       = copy.patientState;
        this.patientZip                         = copy.patientZip;
        this.patientCountry                     = copy.patientCountry;
        this.providerName                       = copy.providerName;
        this.providerNameSource                 = copy.providerNameSource;
        this.providerNameMatched                = copy.providerNameMatched;
        this.providerSSN                        = copy.providerSSN;
        this.providerBirth                      = copy.providerBirth;
        this.providerPractice                   = copy.providerPractice;
        this.providerStreet                     = copy.providerStreet;
        this.providerCity                       = copy.providerCity;
        this.providerState                      = copy.providerState;
        this.providerZip                        = copy.providerZip;
        this.providerCounty                     = copy.providerCounty;
        this.providerAddressSource              = copy.providerAddressSource;
        this.providerPhone                      = copy.providerPhone;
        this.providerLocalId                    = copy.providerLocalId;
        this.providerLocalIdSource              = copy.providerLocalIdSource;
        this.providerDEANumber                  = copy.providerDEANumber;
        this.providerLicense                    = copy.providerLicense;
        this.labName                            = copy.labName;
        this.labId                              = copy.labId;
        this.labPhone                           = copy.labPhone;
        this.labStreet1                         = copy.labStreet1;
        this.labStreet2                         = copy.labStreet2;
        this.labCity                            = copy.labCity;
        this.labState                           = copy.labState;
        this.labZip                             = copy.labZip;
        this.testId                             = copy.testId;
        this.testName                           = copy.testName;
        this.testCodeSystem                     = copy.testCodeSystem;
        this.testPlacerOrderNum                 = copy.testPlacerOrderNum;
        this.testFillerOrderNum                 = copy.testFillerOrderNum;
        this.testDate                           = copy.testDate;
        this.testDateSource                     = copy.testDateSource;
        this.testParentPlacer                   = copy.testParentPlacer;
        this.testParentFiller                   = copy.testParentFiller;
        this.testSpecimenText                   = copy.testSpecimenText;
        this.testDataType                       = copy.testDataType;
        this.testNormalRange                    = copy.testNormalRange;
        this.testAbnormalFlag                   = copy.testAbnormalFlag;
        this.testComment                        = copy.testComment;
        this.messageReceivedDateTime            = copy.messageReceivedDateTime;
        this.mpqSeqNumber                       = copy.mpqSeqNumber;
        this.testResultId                       = copy.testResultId;
        this.testResultName                     = copy.testResultName;
        this.testResultCodeSystem               = copy.testResultCodeSystem;
        this.testResultSubId                    = copy.testResultSubId;
        this.testResultCode                     = copy.testResultCode;
        this.testResultValue                    = copy.testResultValue;
        this.testResultUnits                    = copy.testResultUnits;
        this.testResultStatus                   = copy.testResultStatus;
        this.testPreviousDate                   = copy.testPreviousDate;
        this.conditionName                      = copy.conditionName;
        this.obrAltCode                         = copy.obrAltCode;
        this.obrAltCodeText                     = copy.obrAltCodeText;
        this.obrAltCodeSystem                   = copy.obrAltCodeSystem;
        this.obxAltCode                         = copy.obxAltCode;
        this.obxAltCodeText                     = copy.obxAltCodeText;
        this.obxAltCodeSystem                   = copy.obxAltCodeSystem;
        this.nextReportableResults              = copy.nextReportableResults;
        this.facilityId                         = copy.facilityId;
        this.resultSeq                          = copy.resultSeq;
        this.obrSetId                           = copy.obrSetId;
        this.obxStartSetId                      = copy.obxStartSetId;
        this.obxEndSetId                        = copy.obxEndSetId;
        this.sendingApplication                 = copy.sendingApplication;
        this.sendingFacility                    = copy.sendingFacility;
        this.sendingLocation                    = copy.sendingLocation;
        this.releaseDate                        = copy.releaseDate;
        this.sentInError                        = copy.sentInError;
        this.criticDisplay                      = copy.criticDisplay;
        this.codeDisplay                        = copy.codeDisplay;
    }

    public Long getId() 
    {
        return this.id;
    }
    public void setId(Long id) 
    {
        this.id = id;
    }

    public Code getCode() 
    {
        return this.code;
    }
    public void setCode(Code code) 
    {
        this.code = code;
    }

    public ReportableResult getPreviousReportableResult() 
    {
        return this.previousReportableResult;
    }
    public void setPreviousReportableResult(ReportableResult tblreportableresult) 
    {
        this.previousReportableResult = tblreportableresult;
    }

    public Institution getInstitution() 
    {
        return this.institution;
    }
    public void setInstitution(Institution institution) 
    {
        this.institution = institution;
    }

    public RawMessage getRawMessage() 
    {
        return this.rawMessage;
    }
    public void setRawMessage(RawMessage tblrawhl7) 
    {
        this.rawMessage = tblrawhl7;
    }

    public HL7Producer getProducer() 
    {
        return this.producer;
    }
    public void setProducer(HL7Producer hl7Producer) 
    {
        this.producer = hl7Producer;
    }
    
    public County getCounty() 
    {
        return this.county;
    }
    public void setCounty(County tblcounty) 
    {
        this.county = tblcounty;
    }
    
    public Jurisdiction getJurisdiction() 
    {
        return this.jurisdiction;
    }
    public void setJurisdiction(Jurisdiction tbljurisdiction) 
    {
        this.jurisdiction = tbljurisdiction;
    }
    
    public CriticDef getCritic() 
    {
        return this.critic;
    }
    public void setCritic(CriticDef indicatingCritic) 
    {
        this.critic = indicatingCritic;
    }
    
    public DecidedResultArchive getDecidedResult() 
    {
        return this.decidedResult;
    }
    public void setDecidedResult(DecidedResultArchive decidedResult) 
    {
        this.decidedResult = decidedResult;
    }

    public ManualReviewStatusType getManualReviewStatusType() 
    {
        return this.manualReviewStatusType;
    }
    public void setManualReviewStatusType(ManualReviewStatusType reviewStatus) 
    {
        this.manualReviewStatusType = reviewStatus;
    }

    public String getInstitutionIdType() 
    {
        return this.institutionIdType;
    }
    public void setInstitutionIdType(String institutionidtype) 
    {
        this.institutionIdType = institutionidtype;
    }

    public String getPatientInstitutionMedicalRecordId() 
    {
        return this.patientInstitutionMedicalRecordId;
    }
    public void setPatientInstitutionMedicalRecordId( String patientinstitutionmedicalrecordid ) 
    {
        this.patientInstitutionMedicalRecordId = patientinstitutionmedicalrecordid;
    }

    public String getGlobalPatientId() 
    {
        return this.globalPatientId;
    }
    public void setGlobalPatientId(String globalpatientid) 
    {
        this.globalPatientId = globalpatientid;
    }

    public String getPatientSSN() 
    {
        return this.patientSSN;
    }
    public void setPatientSSN(String patientssn) 
    {
        this.patientSSN = patientssn;
    }

    public String getPatientName() 
    {
        return this.patientName;
    }
    public void setPatientName(String patientname) 
    {
        this.patientName = patientname;
    }

    public Date getPatientBirth() 
    {
        return this.patientBirth;
    }
    public void setPatientBirth(Date patientbirth) 
    {
        this.patientBirth = patientbirth;
    }

    public String getPatientRace() 
    {
        return this.patientRace;
    }
    public void setPatientRace(String patientrace) 
    {
        this.patientRace = patientrace;
    }

    public String getPatientPhone() 
    {
        return this.patientPhone;
    }
    public void setPatientPhone(String patientphone) 
    {
        this.patientPhone = patientphone;
    }

    public String getPatientStreet1() 
    {
        return this.patientStreet1;
    }
    public void setPatientStreet1(String patientstreet1) 
    {
        this.patientStreet1 = patientstreet1;
    }

    public String getPatientStreet2() 
    {
        return this.patientStreet2;
    }
    public void setPatientStreet2(String patientstreet2) 
    {
        this.patientStreet2 = patientstreet2;
    }

    public String getPatientCity() 
    {
        return this.patientCity;
    }
    public void setPatientCity(String patientcity) 
    {
        this.patientCity = patientcity;
    }

    public String getPatientCounty() 
    {
        return this.patientCounty;
    }
    public void setPatientCounty(String patientcounty) 
    {
        this.patientCounty = patientcounty;
    }

    public String getPatientState() 
    {
        return this.patientState;
    }
    public void setPatientState(String patientstate) 
    {
        this.patientState = patientstate;
    }

    public String getPatientZip() 
    {
        return this.patientZip;
    }
    public void setPatientZip(String patientzip) 
    {
        this.patientZip = patientzip;
    }

    public String getPatientCountry() 
    {
        return this.patientCountry;
    }
    public void setPatientCountry(String patientcountry) 
    {
        this.patientCountry = patientcountry;
    }

    public String getProviderName() 
    {
        return this.providerName;
    }
    public void setProviderName(String providername) 
    {
        this.providerName = providername;
    }

    public String getProviderNameMatched() 
    {
        return this.providerNameMatched;
    }
    public void setProviderNameMatched(String providernamematched) 
    {
        this.providerNameMatched = providernamematched;
    }

    public String getProviderSSN() 
    {
        return this.providerSSN;
    }
    public void setProviderSSN(String providerssn) 
    {
        this.providerSSN = providerssn;
    }

    public Date getProviderBirth() 
    {
        return this.providerBirth;
    }
    public void setProviderBirth(Date providerbirth) 
    {
        this.providerBirth = providerbirth;
    }

    public String getProviderPractice() 
    {
        return this.providerPractice;
    }
    public void setProviderPractice(String providerpractice) 
    {
        this.providerPractice = providerpractice;
    }

    public String getProviderStreet() 
    {
        return this.providerStreet;
    }
    public void setProviderStreet(String providerstreet) 
    {
        this.providerStreet = providerstreet;
    }

    public String getProviderCity() 
    {
        return this.providerCity;
    }
    public void setProviderCity(String providercity) 
    {
        this.providerCity = providercity;
    }

    public String getProviderState() 
    {
        return this.providerState;
    }
    public void setProviderState(String providerstate) 
    {
        this.providerState = providerstate;
    }

    public String getProviderZip() 
    {
        return this.providerZip;
    }
    public void setProviderZip(String providerzip) 
    {
        this.providerZip = providerzip;
    }

    public String getProviderCounty() 
    {
        return this.providerCounty;
    }
    public void setProviderCounty(String providercounty) 
    {
        this.providerCounty = providercounty;
    }

    public String getProviderPhone() 
    {
        return this.providerPhone;
    }
    public void setProviderPhone(String providerphone) 
    {
        this.providerPhone = providerphone;
    }

    public String getProviderLocalId() 
    {
        return this.providerLocalId;
    }
    public void setProviderLocalId(String providerlocalid) 
    {
        this.providerLocalId = providerlocalid;
    }

    public String getProviderDEANumber() 
    {
        return this.providerDEANumber;
    }
    public void setProviderDEANumber(String providerdeanumber) 
    {
        this.providerDEANumber = providerdeanumber;
    }

    public String getProviderLicense() 
    {
        return this.providerLicense;
    }
    public void setProviderLicense(String providerlicense) 
    {
        this.providerLicense = providerlicense;
    }

    public String getLabName() 
    {
        return this.labName;
    }
    public void setLabName(String labname) 
    {
        this.labName = labname;
    }

    public String getLabId() 
    {
        return this.labId;
    }
    public void setLabId(String labid) 
    {
        this.labId = labid;
    }

    public String getLabPhone() 
    {
        return this.labPhone;
    }
    public void setLabPhone(String labphone) 
    {
        this.labPhone = labphone;
    }

    public String getLabStreet1() 
    {
        return this.labStreet1;
    }
    public void setLabStreet1(String labstreet1) 
    {
        this.labStreet1 = labstreet1;
    }

    public String getLabStreet2() 
    {
        return this.labStreet2;
    }
    public void setLabStreet2(String labstreet2) 
    {
        this.labStreet2 = labstreet2;
    }
    
    public String getLabCity() 
    {
        return this.labCity;
    }
    public void setLabCity(String labcity) 
    {
        this.labCity = labcity;
    }

    public String getLabState() 
    {
        return this.labState;
    }
    public void setLabState(String labstate) 
    {
        this.labState = labstate;
    }

    public String getLabZip() 
    {
        return this.labZip;
    }
    public void setLabZip(String labzip) 
    {
        this.labZip = labzip;
    }

    public String getTestId() 
    {
        return this.testId;
    }
    public void setTestId(String testid) 
    {
        this.testId = testid;
    }

    public String getTestName() 
    {
        return this.testName;
    }
    public void setTestName(String testname) 
    {
        this.testName = testname;
    }

    public String getTestCodeSystem() 
    {
        return this.testCodeSystem;
    }
    public void setTestCodeSystem(String testcodesys) 
    {
        this.testCodeSystem = testcodesys;
    }

    public String getTestPlacerOrderNum() 
    {
        return this.testPlacerOrderNum;
    }
    public void setTestPlacerOrderNum(String testplacerordernum) 
    {
        this.testPlacerOrderNum = testplacerordernum;
    }

    public String getTestFillerOrderNum() 
    {
        return this.testFillerOrderNum;
    }
    public void setTestFillerOrderNum(String testfillerordernum) 
    {
        this.testFillerOrderNum = testfillerordernum;
    }

    public Date getTestDate() 
    {
        return this.testDate;
    }
    public void setTestDate(Date testdate) 
    {
        this.testDate = testdate;
    }

    public String getTestParentPlacer() 
    {
        return this.testParentPlacer;
    }
    public void setTestParentPlacer(String testparentplacer) 
    {
        this.testParentPlacer = testparentplacer;
    }

    public String getTestParentFiller() 
    {
        return this.testParentFiller;
    }
    public void setTestParentFiller(String testparentfiller) 
    {
        this.testParentFiller = testparentfiller;
    }

    public String getTestSpecimenText() 
    {
        return this.testSpecimenText;
    }
    public void setTestSpecimenText(String testspecimentext) 
    {
        this.testSpecimenText = testspecimentext;
    }

    public String getTestDataType() 
    {
        return this.testDataType;
    }
    public void setTestDataType(String testdatatype) 
    {
        this.testDataType = testdatatype;
    }

    public String getTestNormalRange() 
    {
        return this.testNormalRange;
    }
    public void setTestNormalRange(String testnormalrange) 
    {
        this.testNormalRange = testnormalrange;
    }

    public String getTestAbnormalFlag() 
    {
        return this.testAbnormalFlag;
    }
    public void setTestAbnormalFlag( String testabnormalflagParm ) 
    {
        this.testAbnormalFlag = testabnormalflagParm;
    }

    public String getTestComment() 
    {
        return this.testComment;
    }
    public void setTestComment(String testcomment) 
    {
        this.testComment = testcomment;
    }

    public Date getMessageReceivedDateTime() 
    {
        return this.messageReceivedDateTime;
    }
    public void setMessageReceivedDateTime(Date messageReceivedDateTime) 
    {
        this.messageReceivedDateTime = messageReceivedDateTime;
    }

    public String getMpqSeqNumber() 
    {
        return this.mpqSeqNumber;
    }
    public void setMpqSeqNumber(String mpqSeqNumber) 
    {
        this.mpqSeqNumber = mpqSeqNumber;
    }

    public String getTestResultId() 
    {
        return this.testResultId;
    }
    public void setTestResultId(String testresultid) 
    {
        this.testResultId = testresultid;
    }

    public String getTestResultName() 
    {
        return this.testResultName;
    }
    public void setTestResultName(String testresultname) 
    {
        this.testResultName = testresultname;
    }

    public String getTestResultCodeSystem() 
    {
        return this.testResultCodeSystem;
    }
    public void setTestResultCodeSystem(String testresultcodesys) 
    {
        this.testResultCodeSystem = testresultcodesys;
    }

    public String getTestResultSubId() 
    {
        return this.testResultSubId;
    }
    public void setTestResultSubId(String testresultsubid) 
    {
        this.testResultSubId = testresultsubid;
    }

    public String getTestResultCode() 
    {
        return this.testResultCode;
    }
    public void setTestResultCode(String testresultcode) 
    {
        this.testResultCode = testresultcode;
    }

    public String getTestResultValue() 
    {
        return this.testResultValue;
    }
    public void setTestResultValue(String testresultvalue) 
    {
        this.testResultValue = testresultvalue;
    }

    public String getTestResultUnits() 
    {
        return this.testResultUnits;
    }
    public void setTestResultUnits(String testresultunits) 
    {
        this.testResultUnits = testresultunits;
    }

    public Date getTestPreviousDate() 
    {
        return this.testPreviousDate;
    }
    public void setTestPreviousDate(Date testpreviousdate) 
    {
        this.testPreviousDate = testpreviousdate;
    }

    public String getConditionName() 
    {
        return this.conditionName;
    }
    public void setConditionName(String conditionName) 
    {
        this.conditionName = conditionName;
    }

    public String getObrAltCode() 
    {
        return this.obrAltCode;
    }
    public void setObrAltCode(String obraltcode) 
    {
        this.obrAltCode = obraltcode;
    }

    public String getObrAltCodeText() 
    {
        return this.obrAltCodeText;
    }
    public void setObrAltCodeText(String obraltcodetext) 
    {
        this.obrAltCodeText = obraltcodetext;
    }

    public String getObrAltCodeSystem() 
    {
        return this.obrAltCodeSystem;
    }
    public void setObrAltCodeSystem(String obraltcodesys) 
    {
        this.obrAltCodeSystem = obraltcodesys;
    }

    public String getObxAltCode() 
    {
        return this.obxAltCode;
    }
    public void setObxAltCode(String obxaltcode) 
    {
        this.obxAltCode = obxaltcode;
    }

    public String getObxAltCodeText() 
    {
        return this.obxAltCodeText;
    }
    public void setObxAltCodeText(String obxaltcodetext) 
    {
        this.obxAltCodeText = obxaltcodetext;
    }

    public String getObxAltCodeSystem() 
    {
        return this.obxAltCodeSystem;
    }
    public void setObxAltCodeSystem(String obxaltcodesys) 
    {
        this.obxAltCodeSystem = obxaltcodesys;
    }

    public String getProviderNameSource() 
    {
        return this.providerNameSource;
    }
    public void setProviderNameSource(String providernamesource) 
    {
        this.providerNameSource = providernamesource;
    }

    public String getProviderAddressSource() 
    {
        return this.providerAddressSource;
    }
    public void setProviderAddressSource(String provideraddresssource) 
    {
        this.providerAddressSource = provideraddresssource;
    }

    public String getProviderLocalIdSource() 
    {
        return this.providerLocalIdSource;
    }
    public void setProviderLocalIdSource(String providerlocalidsource) 
    {
        this.providerLocalIdSource = providerlocalidsource;
    }

    public String getTestDateSource() 
    {
        return this.testDateSource;
    }
    public void setTestDateSource(String testdatesource) 
    {
        this.testDateSource = testdatesource;
    }

    public String getTestPlacerOrderNumSource() 
    {
        return this.testPlacerOrderNumSource;
    }
    public void setTestPlacerOrderNumSource(String testplacerordernumsource) 
    {
        this.testPlacerOrderNumSource = testplacerordernumsource;
    }

    public String getTestFillerOrderNumSource() 
    {
        return this.testFillerOrderNumSource;
    }
    public void setTestFillerOrderNumSource(String testfillerordernumsource) 
    {
        this.testFillerOrderNumSource = testfillerordernumsource;
    }

    public String getFacilityId() 
    {
        return this.facilityId;
    }
    public void setFacilityId(String facilityid) 
    {
        this.facilityId = facilityid;
    }

    public Character getPatientSex() 
    {
        return this.patientSex;
    }
    public void setPatientSex(Character patientsex) 
    {
        this.patientSex = patientsex;
    }

    public Character getTestResultStatus() 
    {
        return this.testResultStatus;
    }
    public void setTestResultStatus(Character testresultstatus) 
    {
        this.testResultStatus = testresultstatus;
    }

    public Long getResultSeq() 
    {
        return this.resultSeq;
    }
    public void setResultSeq(Long resultSeq) 
    {
        this.resultSeq = resultSeq;
    }

    public Set<ReportableResult> getNextReportableResults() 
    {
        return this.nextReportableResults;
    }
    public void setNextReportableResults( Set<ReportableResult> tblreportableresults) 
    {
        this.nextReportableResults = tblreportableresults;
    }

    public int getObrSetId() 
    {
        return obrSetId;
    }
    public void setObrSetId(int obrSetId) 
    {
        this.obrSetId = obrSetId;
    }

    public int getObxEndSetId() 
    {
        return obxEndSetId;
    }
    public void setObxEndSetId(int obxEndSetId) 
    {
        this.obxEndSetId = obxEndSetId;
    }

    public int getObxStartSetId() 
    {
        return obxStartSetId;
    }
    public void setObxStartSetId(int obxStartSetId) 
    {
        this.obxStartSetId = obxStartSetId;
    }    
    
    public String getSendingApplication() 
    {
        return sendingApplication;
    }
    public void setSendingApplication(String app) 
    {
        sendingApplication = app;
    }
    
    public String getSendingFacility() 
    {
        return sendingFacility;
    }
    public void setSendingFacility(String fac) 
    {
        sendingFacility = fac;
    }
    
    public String getSendingLocation() 
    {
        return sendingLocation;
    }
    public void setSendingLocation(String loc) 
    {
        sendingLocation = loc;
    }

    public Date getReleaseDate() 
    {
        return this.releaseDate;
    }
    public void setReleaseDate(Date releaseDate) 
    {
        this.releaseDate = releaseDate;
    }

	public Long getEncounterId() 
	{
		return encounterId;
	}
	public void setEncounterId(Long encounterId)
	{
		this.encounterId = encounterId;
	}

	public Boolean getSentInError() 
	{
		return sentInError;
	}
	public void setSentInError(Boolean sentInError) 
	{
		this.sentInError = sentInError;
	}

	public String getCriticDisplay() 
	{
		return criticDisplay;
	}
	public void setCriticDisplay(String criticDisplay) 
	{
		this.criticDisplay = criticDisplay;
	}

	public String getCodeDisplay() 
	{
		return codeDisplay;
	}
	public void setCodeDisplay(String codeDisplay) 
	{
		this.codeDisplay = codeDisplay;
	}
}
